from aiogram.types import KeyboardButton
from buttons.reply.reply_buttons_text import *

to_recommendations_button = KeyboardButton(TO_RECOMMENDATIONS_BUTTON_TEXT)
to_categories_button = KeyboardButton(TO_CATEGORIES_BUTTON_TEXT)
to_personal_button = KeyboardButton(TO_PERSONAL_BUTTON_TEXT)

skip_button = KeyboardButton(SKIP_BUTTON_TEXT)

list_channels_button = KeyboardButton(LIST_CHANNELS_BUTTON_TEXT)

add_personal_channels_button = KeyboardButton(ADD_PERSONAL_CHANNELS_BUTTON_TEXT)

add_general_channels_button = KeyboardButton(ADD_GENERAL_CHANNELS_BUTTON_TEXT)
add_general_category_button = KeyboardButton(ADD_GENERAL_CATEGORY_BUTTON_TEXT)

delete_general_channels_button = KeyboardButton(DELETE_GENERAL_CHANNELS_BUTTON_TEXT)
delete_general_category_button = KeyboardButton(DELETE_GENERAL_CATEGORY_BUTTON_TEXT)

add_delete_user_categories_button = KeyboardButton(ADD_OR_DELETE_USER_CATEGORIES_BUTTON_TEXT)

start_button = KeyboardButton(START_BUTTON_TEXT)
to_admin_panel_button = KeyboardButton(TO_ADMIN_PANEL_BUTTON_TEXT)

delete_channels_button = KeyboardButton(DELETE_CHANNELS_BUTTON_TEXT)

like_button = KeyboardButton(LIKE_BUTTON_TEXT)
dislike_button = KeyboardButton(DISLIKE_BUTTON_TEXT)
