ADD_PREMIUM_CHANNELS_BUTTON_TEXT = 'Добавить премиальные каналы'
ADD_CATEGORY_CHANNELS_BUTTON_TEXT = 'Добавить каналы в категории'
ADD_CATEGORY_BUTTON_TEXT = 'Добавить категорию'
DELETE_CATEGORIES_CHANNELS_BUTTON_TEXT = 'Удалить каналы из категорий'
DELETE_PREMIUM_CHANNELS_BUTTON_TEXT = 'Удалить премиальные каналы'
DELETE_CATEGORY_BUTTON_TEXT = 'Удалить категории'
LIST_CATEGORIES_CHANNELS_BUTTON_TEXT = 'Список каналов из категорий'
LIST_PREMIUM_CHANNELS_BUTTON_TEXT = 'Список премиальных каналов'
LIST_CATEGORIES_BUTTON_TEXT = 'Список категорий'
DELETE_COEFFICIENTS = 'Удалить коэффициенты'
ADD_COEFFICIENTS = 'Добавить коэффициенты'
LIST_COEFFICIENTS = 'Список коэффициентов'
LIST_STATISTIC = 'Статистика'


