from aiogram.types import KeyboardButton

from buttons.reply.lents import lents_buttons_text

recommendations_button = KeyboardButton(lents_buttons_text.recommendations_button_text)
categories_button = KeyboardButton(lents_buttons_text.categories_button_text)
personal_button = KeyboardButton(lents_buttons_text.personal_button_text)
skip_button = KeyboardButton(lents_buttons_text.skip_button_text)
list_channels_button = KeyboardButton(lents_buttons_text.list_channels_button_text)
add_channels_button = KeyboardButton(lents_buttons_text.add_channels_button_text)
delete_channels = KeyboardButton(lents_buttons_text.delete_channels_button_text)

like_button = KeyboardButton(lents_buttons_text.dislike_button_text)
dislike_button = KeyboardButton(lents_buttons_text.like_button_text)
