recommendations_button_text = 'Рекомендации 🔍'
categories_button_text = 'По категориям 🗂️'
personal_button_text = 'Личная лента 🌟'
skip_button_text = 'Дальше ➤'
list_channels_button_text = 'Список каналов 📋'
add_channels_button_text = 'Добавить каналы ➕'
delete_channels_button_text = 'Удалить каналы 🚫'

like_button_text = '❤'
dislike_button_text = '👎'
