TO_RECOMMENDATIONS_BUTTON_TEXT = 'Рекомендации 🔍'
TO_CATEGORIES_BUTTON_TEXT = 'По категориям 🗂️'
TO_PERSONAL_BUTTON_TEXT = 'Личная лента 🌟'
TO_ADMIN_PANEL_BUTTON_TEXT = 'Админ панель 👑'

SKIP_BUTTON_TEXT = 'Дальше ➤'
START_BUTTON_TEXT = 'Старт'

LIKE_BUTTON_TEXT = '❤'
DISLIKE_BUTTON_TEXT = '👎'