# Ответы бота
START_MESSAGE_FOR_NEW = 'Привет! Я бот для управления каналами в Telegram.'
START_MESSAGE_FOR_OLD = 'Рады снова вас приветствовать!'
ADD_CHANNELS_MESSAGE = 'Напишите ссылку одного или нескольких каналов через запятую. Вы можете использовать формат https://t.me/название_канала или @название_канала'
DELETE_CHANNEL_MESSAGE = 'Нажмите на канал из списка, который хотите удалить'
EMPTY_USER_LIST_CHANNELS_MESSAGE = 'Список ваших каналов пуст'
CHANNELS_ADDED_MESSAGE = 'Были добавлены каналы:\n'
CHANNELS_NOT_ADDED_MESSAGE = 'Не удалось добавить каналы:\n'
CHANNELS_ALREADY_ADDED_MESSAGE = 'Каналы уже были добавлены ранее:\n'
POST_FROM_CHANNEL_MESSAGE = '\n\nПост с канала @{channel_username}'
ADDED_CHANNELS_MESSAGE = 'Добавленные каналы:\n'
POST_ARE_OVER = 'Посты закончились ☹'
CHANNELS_ADDED_WITH_CATEGORY_MESSAGE = 'Были добавлены каналы с категорией `<code>{category}</code>`:\n'