from keyboards.admin.reply import admin_reply_buttons_texts, admin_reply_keyboards
from keyboards.categories.reply import categories_reply_buttons_texts, categories_reply_keyboards
from keyboards.personal.reply import personal_reply_buttons_texts, personal_reply_keyboards
from keyboards.recommendations.reply import recommendations_reply_buttons_texts, recommendations_reply_keyboards
from keyboards.general.reply import general_reply_buttons_texts, general_reply_keyboards, general_reply_buttons

from keyboards.admin.inline import admin_inline_keyboards
from keyboards.personal.inline import personal_inline_keyboards

from keyboards.general.inline import general_inline_buttons_texts
