from keyboards.admin.reply import admin_reply_buttons_texts
from keyboards.categories.reply import categories_reply_buttons_texts
from keyboards.personal.reply import personal_reply_buttons_texts
from keyboards.recommendations.reply import recommendations_reply_buttons_texts
from keyboards.general.reply import general_reply_buttons_texts

from keyboards.admin.reply import admin_reply_keyboards
from keyboards.categories.reply import categories_reply_keyboards
from keyboards.personal.reply import personal_reply_keyboards
from keyboards.recommendations.reply import recommendations_reply_keyboards

