TO_RECOMMENDATIONS_BUTTON_TEXT = 'Рекомендации 🔍'
TO_CATEGORIES_BUTTON_TEXT = 'По категориям 🗂️'

SKIP_BUTTON_TEXT = 'Дальше ➤'
START_BUTTON_TEXT = 'Старт'

LIST_USER_CHANNELS_BUTTON_TEXT = 'Список📋'
ADD_USER_CHANNELS_BUTTON_TEXT = 'Добавить➕'
DELETE_USER_CHANNELS_BUTTON_TEXT = 'Удалить🗑️'

LIKE_BUTTON_TEXT = '❤'
DISLIKE_BUTTON_TEXT = '👎'
